site_name: 坤仪·万象
site_url: https://docs.kuintessence.com
theme:
  name: material
  logo: 'img/logo.png'
  favicon: 'img/logo_icon.png'
  language: 'zh'
  icon:
    logo: material/library 
    features:
    - content.code.copy
    - content.code.annotate  
  palette:
    - scheme: default # 日间模式
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: 切换夜间模式
    - scheme: slate # 日间模式
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换日间模式
  nav_style: light
  highlightjs: true
nav:
- 首页: index.md
- 产品介绍: 
    - 坤仪·万象: guide/server/index.md
    - 坤仪·万象 使用者门户: guide/user/index.md
    - 坤仪·万象 提供者门户: guide/provider/index.md
    - 内容库: guide/contenthub/index.md
- 快速入门: 
    - 首页: guide/start/index.md
    - 注册用户: guide/start/register.md
    - 部署坤仪·万象: guide/start/composek10e.md
    - 配置使用者门户: guide/start/composek10euser.md
    - 提交计算任务: guide/start/quick_start.md
- 安装部署:
    - 网络端口说明: installation/network_port.md
    - Docker部署:
        - 环境要求: installation/setup_docker/requirements.md
        - 在线安装: installation/setup_docker/online_install.md
markdown_extensions:
  - markdown.extensions.attr_list
  - md_in_html # 图片
  - pymdownx.highlight # 高亮
  - attr_list # 按钮
  - pymdownx.inlinehilite # 行内高亮
  - pymdownx.snippets
  # 提示，警告栏
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # 内容标签
  - pymdownx.tabbed:
      alternate_style: true
  - tables # 表格
  - footnotes # 注脚
  # 图标
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search